services:
  minecraft-bot-bob:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minecraft-bot-bob
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MINECRAFT_USERNAME=BobBot
      # For Linux, use the special Docker DNS name
      - MINECRAFT_HOST=host.docker.internal
      - MINECRAFT_ROLE=builder
      - NEVERMINED_API_KEY=${BOB_NEVERMINED_API_KEY}

    ports:
      - "3001:3001"
    volumes:
      - shared_data:/app/server/data
    networks:
      - minecraft-network
    # For Linux, add this to make host.docker.internal work
    extra_hosts:
      - "host.docker.internal:host-gateway"

  minecraft-bot-alice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minecraft-bot-alice
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3002
      - MINECRAFT_USERNAME=AliceBot
      # For Linux, use the special Docker DNS name
      - MINECRAFT_HOST=host.docker.internal
      - MINECRAFT_ROLE=merchant
      - NEVERMINED_API_KEY=${ALICE_NEVERMINED_API_KEY}
    ports:
      - "3002:3002"
    volumes:
      - shared_data:/app/server/data
    networks:
      - minecraft-network
    # For Linux, add this to make host.docker.internal work
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  shared_data:

networks:
  minecraft-network:
    driver: bridge 